name: E2E
on: [pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      CYPRESS_CACHE_FOLDER: ./node_modules/cache-cypress
      UNIVERSAL_SERVER: http://localhost:4000
      STATIC_SERVER: http://localhost:8080
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Build demo
        run: npm run build

concurrency:
  group: integration-e2e-${{ github.head_ref }}
  cancel-in-progress: true
